package com.workmotion.employeemanagementsystem.base.localization;

/**
 * @author Alber Rashad
 * @created 01/11/2022
 * @description
 */
public interface CoreMessageConstants {
    String REQUEST_SUCCESS = "REQUEST_SUCCESS";
    String REQUEST_FAILED = "REQUEST_FAILED";
    String UNEXPECTED_ERROR = "UNEXPECTED_ERROR";
    String MISSING_PARAMETER = "MISSING_PARAMETER";
    String MEDIA_TYPE_NOT_SUPPORTED = "MEDIA_TYPE_NOT_SUPPORTED";
    String METHOD_NOT_FOUND = "METHOD_NOT_FOUND";
    String DATABASE_ERROR = "DATABASE_ERROR";
    String PARAMETER_MISMATCH = "PARAMETER_MISMATCH";
    String MALFORMED_JSON_REQUEST = "MALFORMED_JSON_REQUEST";
    String ERROR_WRITING_JSON = "ERROR_WRITING_JSON";
    String USERNAME_IS_MISSING = "USERNAME_IS_MISSING";
    String USER_IS_NOT_FOUND = "USER_IS_NOT_FOUND";
    String PASSWORD_EMPTY = "PASSWORD_EMPTY";
    String UNAUTHORIZED = "UNAUTHORIZED";
    String FORBIDDEN = "FORBIDDEN";
    String VALIDATION_ERROR = "VALIDATION_ERROR";
    String TRANSACTION_SYSTEM_ERROR = "TRANSACTION_SYSTEM_ERROR";
    String USER_ALREADY_EXIST="USER_ALREADY_EXIST";
    String ITEM_IS_NOT_FOUND = "ITEM_IS_NOT_FOUND";
    String INCORRECT_USERNAME_OR_PASSWORD="INCORRECT_USERNAME_OR_PASSWORD";
    String INVALID_CODE="INVALID_CODE";
    String ITEM_ALREADY_EXIST="ITEM_ALREADY_EXIST";

    String IS_NOT_FOUND = "IS_NOT_FOUND";
}
